openapi: 3.0.0
info:
  version: "1.0.0"
  title: API de doh
  description: Documentaci贸n de la API de Dns-Over-Https de la materia 75.43 Introducci贸n a Sistemas Distribuidos

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicaci贸n
paths:

  /domains/{domain_name}:
    get:
      operationId: "api.domains.obtain_ip"
      tags:
        - "Domains"
      summary: "IPs dominios"
      description: "Obtiene la IP asociada a un dominio en particular, pudiendo ser este un custom domain creado previamente."
      parameters:
        - in: path
          name: domain_name
          required: true
          schema:
            type: string
          description: El domain name del cual queremos obtener su ip
      responses:
        200:
          description: "Informacion del dominio encontrado exitosamente"
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Domain'
        404:
          description: "No existe el dominio en el sistema ni se pudo resolver mediante DNS"
        504:
          description: "Timeout al tratar de conseguir las IPs del dominio"

  /custom-domains:
    get:
      operationId: "api.domains.get_domains"
      tags:
        - "Custom domains"
      summary: "Obtiene los custom domains del sistema"
      description: "Obtiene los custom domains del sistema que contienen 'domain_name'"
      parameters:
        - in: query
          name: domain_name
          required: false
          schema:
            type: string
          description: parte del nombre del dominio que se quiere buscar
      responses:
        200:
          description: "Dominios que cumplen con la condicion de busqueda"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'

    post:
      operationId: "api.domains.add_custom_domain"
      tags:
        - 'Custom domains'
      summary: "Agrega un nuevo dominio custom"
      description: "Carga un nuevo dominio custom en el sistema con su correspondiente IP"
      requestBody:
        required: true
        x-body-name: 'custom-domain'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputCustomDomain'
      responses:
        201:
          description: "Operacion de carga exitosa"
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Domain'
        400: 
          description: "Ya se ha cargado el dominio en el sistema o el JSON esta mal formado"
    put:
      operationId: "api.domains.edit_domain"
      tags: 
        - 'Edit domain'
      summary: 'Modifica ips'
      description: 'Modifica la ip de un dominio dado'
      requestBody:
        required: true
        x-body-name: 'edit-domain'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputCustomDomain'
      responses:
        200:
          description: "Modificacion exitosa"
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Domain'
        404:
          description: "No existe el dominio en el sistema, no se puede modificar"
        400:
          description: "El request body esta mal formado"
  /custom-domains/{domain_name}:

    delete:
      operationId: "api.domains.delete_domain"
      tags:
        - "Delete domain"
      summary: "Deletes domain info"
      description: "Deletes domain info from the system"
      parameters:
        - in: path
          name: domain_name
          required: true
          schema:
            type: string
          description: El nombre del dominio a borrar
      responses:
        200:
          description: "Eliminacion exitosa"
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/DeleteDomain'
        404:
          description: "No se encuentra el dominio"

 
# Declaraci贸n de tipos de datos
components:
  schemas:
    Error:
      type: "object"
      properties:
        codigo:
          type: "number"
        mensaje:
          type: "string"
    Domain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
        custom:
          type: "boolean"
    InputCustomDomain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
    DeleteDomain:
      type: "object"
      properties:
        domain:
          type: "string"